# Lecture 4 Lab Exerices
* Harshin Pathak
* Self Assesment:
  Overall, this assignment was pretty helpful. Question 6.6) took me quite some time as I am not too comfortable with working with strings! I believe this is because I have never really worked with a list of strings in the past at all. I will say that its great to get more practice regarding creating functions that have loops and list comprehension principles. The last three questions were pretty straightforward. I did refer back to the textbook to solve those questions just to get a template for the solution. I will say 7.9) was "enjoyable" in a sense that I have a decent amount of experience with indexing and slicing arrays on Matlab through previous internship experience as an engineer. As a result, that is something I feel very comfortable with but I still want to improve!

## 6.6) Data Science: Duplicate Word Removal
In this question, I created a function that removed duplicates from an array of words, and sorted them in alphabetical order. I first initiated a function with "inputlist" being a list of words. Next I created an empty list that would be filled with exclusive words from "inputlist" called "exclusive_list". Once all values from "inputlist" were compared with values from "exclusive_list", "exclusive_list" was sorted by alphabetical order creating our resultant: "sorted_list". Values from "sorted_list" were then outputted one by one.


In [84]:

# Initiate function with "inputlist" being a list of words
def data_wrangle(inputlist):

    # Create an empty list that will be filled with exclusive words from "inputlist"
    exclusive_list = []

    # For every word in inputlist, covert said word into lowercase
    for word in inputlist:
        
        word = word.lower()

        # Add all exclusive words to the list "exclusive list"
        if word not in exclusive_list:
            
            exclusive_list.append(word)

    # "sorted_list" is "exclusive_list" in alphabetical order
    sorted_list = sorted(exclusive_list)

    # print every unique word in alphabetical order with one word per line
    for word in sorted_list:
        
        print(f"{word}")
       
    # Return "sorted_list" if needed
    return sorted_list
    

    
        
    

In [108]:
# Test Sentence 1
" A dog ran home after he saw a dog"

inputlist = ['A', 'dog', 'ran', 'home', 'after', 'he', 'saw', 'a', 'dog']

sorted_list = data_wrangle(inputlist)

a
after
dog
he
home
ran
saw


In [106]:
# Test Sentence 2
" Robert's dad believes Robert Horry is the greatest athlete as he has seven rings "

inputlist = ["Robert's", 'dad', 'believes', 'Robert', 'Horry', 'is', 'the', 'greatest', 'athlete',
            'as', 'he', 'has', 'seven', 'rings']

sorted_list = data_wrangle(inputlist)


as
athlete
believes
dad
greatest
has
he
horry
is
rings
robert
robert's
seven
the


In [111]:
# Test Sentence 3
" He ran for fifteen miles opposite to the direction the river's current ran "

inputlist = ['He', 'ran', 'fifteen', 'miles', 'opposite', 'to', 'the', 'direction', 'the',
            "river's", 'current', 'ran']

sorted_list = data_wrangle(inputlist)

current
direction
fifteen
he
miles
opposite
ran
river's
the
to


## 6.9) Dictionary Manipulations
In this question, I carried out some elementary dictionay manipulations with the help of some chapter 6 examples from the textbook



In [119]:
# Create Dictionary

tlds = {'Canada': 'ca', 'United States': 'us', 'Mexico': 'mx'}

In [125]:
# a. Check whether the dictionary contains the key 'Canada'

'Canada' in tlds

True

In [127]:
# b. Check whether the dictionary contains the key 'France'

'France' in tlds

False

In [169]:
# c. Iterate through the key–value pairs and display them in two-column format.

for key, value in tlds.items():
    print(f"{key:>},{value:}")

Canada,ca
United States,us
Mexico,mx


In [171]:
# d. Add the key-value pair 'Sweden' and 'sw' (which is incorrect)

tlds['Sweden'] = 'sw'


In [173]:
# e. Update the value for the key 'Sweden' to 'se'

del tlds['Sweden']

tlds['Sweden'] = 'se'

In [175]:
# f. Use a dictionary comprehension to reverse the keys and values.

# Used dictionary comprehension to create a new dictionary by flipping the order of the "template" dict: tlds
tlds_reversed = {symbol: name for name, symbol in tlds.items()}

tlds_reversed


{'ca': 'Canada', 'us': 'United States', 'mx': 'Mexico', 'se': 'Sweden'}

In [185]:
# g. With the result of part (f), use a dictionary comprehension to convert the country names to all uppercase letters.

tlds_reversed_upper = {symbol: name.upper() for symbol, name in tlds_reversed.items()}

tlds_reversed_upper

{'ca': 'CANADA', 'us': 'UNITED STATES', 'mx': 'MEXICO', 'se': 'SWEDEN'}

## 7.2) Broadcasting. LabAssist: Model code after broadcasting examples in 7.7
In this question I utilized numpy and broadcasting (as shown in 7.7) to carry out certain array operations


In [204]:
import numpy as np

array = np.arange(0,4).reshape(2,2)

array

array([[0, 1],
       [2, 3]])

In [214]:
# a) Cube every element of the array

array ** 3


array([[ 0,  1],
       [ 8, 27]], dtype=int32)

In [212]:
# b) Add 7 to every value of the array

array + 7

array([[ 7,  8],
       [ 9, 10]])

In [216]:
# c) Multiply every array element by 2

array * 2

array([[0, 2],
       [4, 6]])

## 7.9 Data Science: Index and Slicing Arrays. LabAssist: model code after 7.10
In this question, I used index and slicing principles to retrieve certain values from an array

In [221]:
# Create Array as described by problem statement
array = np.arange(1,16).reshape(3,5)
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [225]:
# a) select row 2

array[2,:]

array([11, 12, 13, 14, 15])

In [227]:
# b) select column 4

array[:,4]

array([ 5, 10, 15])

In [233]:
# c) select rows 0 and 1 

array[0:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [235]:
# d) Select columns 2-4

array[:, 2:5]

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15]])

In [237]:
# e) Select the element that is in row 1 and column 4

array[1,4]

10

In [253]:
# f) Select all elements from rows 1 and 2 that are in columns 0, 2 and 4
array[1:3, [0,2,4]]

array([[ 6,  8, 10],
       [11, 13, 15]])